In [1]:
import numpy as np

In [10]:
for i in range(5):
    print(i)

0
1
2
3
4


In [12]:
a = [0,1,2,3,4]
for i in a:
    print(i)
print("---------")
for i in range(5):
    print(f"{a[i]}")

0
1
2
3
4
---------
0
1
2
3
4


In [32]:
arr = np.arange(6)


In [57]:
print(arr)
arr


[0 1 2 3 4 5]


array([0, 1, 2, 3, 4, 5])

In [20]:
for i in arr:
    print(i)

0
1
2
3
4
5


In [31]:
arr.shape

(6,)


# Creating a list of 10 numbers

In [35]:
my_list = []
print(my_list)
for i in range(10):
    my_list.append(i)
    print(my_list)
my_list

[]
[0]
[0, 1]
[0, 1, 2]
[0, 1, 2, 3]
[0, 1, 2, 3, 4]
[0, 1, 2, 3, 4, 5]
[0, 1, 2, 3, 4, 5, 6]
[0, 1, 2, 3, 4, 5, 6, 7]
[0, 1, 2, 3, 4, 5, 6, 7, 8]
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [39]:
my_np_list = np.arange(10)
print(my_np_list)
my_np_list

[0 1 2 3 4 5 6 7 8 9]


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

# Creating number data sets using numpy

In [41]:
a = np.array([0,1,2,3,4,5,6,7,8,9])
print(a)
a

[0 1 2 3 4 5 6 7 8 9]


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [70]:
my_list = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
a = np.array(my_list)
print(a)
a

[0 1 2 3 4 5 6 7 8 9]


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

## Assignemnt
Given a single dimesional list [1, 2, 3, 4, 5, 6, 7, 8, 9]
Find multi-dimensinal list [[1,2,3],[4,5,6],[7,8,9]]

In [101]:
a = [1,2,3,4,5,6,7,8,9]

c = []

for i in range(0,7,3):
    b = []
    for j in range(3):
        b.append(a[i+j])
    c.append(b)

print(c)

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]


# Creating a matrix

In [59]:
m = [
    1,2,3,
    4,5,6,
    7,8,9
]
print(m)
m


[1, 2, 3, 4, 5, 6, 7, 8, 9]


[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [60]:
np.shape(m)

(9,)

In [55]:
m_1 = [
    [1,2,3],
    [4,5,6],
    [7,8,9]
]

print(m_1)
m_1

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]


[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [56]:
m_1_ar = np.array(m_1)
print(m_1_ar)
m_1_ar

[[1 2 3]
 [4 5 6]
 [7 8 9]]


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [64]:
np_m = np.arange(1,10)
np_m

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [65]:
np.shape(np_m)

(9,)

In [73]:
np_m_reshape = np_m.reshape(3,3)
print(np_m_reshape)
np_m_reshape

[[1 2 3]
 [4 5 6]
 [7 8 9]]


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

# Addition of Matrix usning Numpy Arrays

In [74]:
matrix_1 = np.arange(1,10)
matrix_2 = np.arange(10,100,10)

In [75]:
matrix_1

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [76]:
matrix_2

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [77]:
matrix_1 + matrix_2

array([11, 22, 33, 44, 55, 66, 77, 88, 99])

In [79]:
matrix_1.reshape(3,3) + matrix_2.reshape(3,3)

array([[11, 22, 33],
       [44, 55, 66],
       [77, 88, 99]])

# Addition of Matrix using Python List
## Assignment

Create 2 matrices and then sum the matrices


In [80]:
mat_1 = [
    [1,2,3],
    [4,5,6],
    [7,8,9]
]

mat_2 = [
    [10,20,30],
    [40,50,60],
    [70,80,90]
]

### Iteration 1 (simply adding)

In [85]:
mat_1

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [82]:
mat_2

[[10, 20, 30], [40, 50, 60], [70, 80, 90]]

In [83]:
mat_1 + mat_2

[[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 20, 30], [40, 50, 60], [70, 80, 90]]

### Iteration 2 (converting to np_array then adding)

In [86]:
mat_1_np = np.array(mat_1)
mat_2_np = np.array(mat_2)

In [87]:
mat_1_np

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [88]:
mat_2_np

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [89]:
mat_1_np + mat_2_np

array([[11, 22, 33],
       [44, 55, 66],
       [77, 88, 99]])

### Iteration 3 (treating as pure python lists and using for loop)

In [106]:
final = []
for i in range(3):
    mat_1_temp = mat_1[i]
    mat_2_temp = mat_2[i]
    for j in range(3):
        final.append(mat_1_temp[j]+mat_2_temp[j])
print(final)

[11, 22, 33, 44, 55, 66, 77, 88, 99]


In [103]:
# convert to multi-dimensional Using Arrays
final_array = np.array(final)
final_reshaped = final_array.reshape(3,3)
print(final_reshaped)
final_reshaped

[[11 22 33]
 [44 55 66]
 [77 88 99]]


array([[11, 22, 33],
       [44, 55, 66],
       [77, 88, 99]])

In [108]:
# convert to multi-dimensional Using lists only

final_multi = []

for i in range(0,7,3):
    final_sub = []
    for j in range(3):
        final_sub.append(final[i+j])
    final_multi.append(final_sub)

print(final_multi)

[[11, 22, 33], [44, 55, 66], [77, 88, 99]]
